"""add wallet constraints

Revision ID: 097b615db9fc
Revises: f18e8f7a5288
Create Date: 2026-08-27 13:36:47.812610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097b615db9fc'
down_revision: Union[str, Sequence[str], None] = 'f18e8f7a5288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_wallets_user_id_currency', 'wallets', ['user_id', 'currency'])
    op.create_check_constraint(op.f('ck_wallets_currency_length'), 'wallets', 'char_length(currency) = 3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_wallets_currency_length'), 'wallets', type_='check')
    op.drop_constraint('uq_wallets_user_id_currency', 'wallets', type_='unique')
    # ### end Alembic commands ###
