"""create transactions

Revision ID: 3ba39dd1e733
Revises: 88fcb4f3e811
Create Date: 2026-09-07 15:27:45.020218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba39dd1e733'
down_revision: Union[str, Sequence[str], None] = '88fcb4f3e811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_wallet_id', sa.Integer(), nullable=True),
    sa.Column('receiver_wallet_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_wallet_id'], ['wallets.id'], name=op.f('fk_transactions_receiver_wallet_id_wallets')),
    sa.ForeignKeyConstraint(['sender_wallet_id'], ['wallets.id'], name=op.f('fk_transactions_sender_wallet_id_wallets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_receiver_wallet_id'), 'transactions', ['receiver_wallet_id'], unique=False)
    op.create_index(op.f('ix_transactions_sender_wallet_id'), 'transactions', ['sender_wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_sender_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver_wallet_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
