"""add transaction idempotency key

Revision ID: 5d19aa54b82d
Revises: 91bf27a6ecf5
Create Date: 2026-09-21 08:23:56.008796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d19aa54b82d'
down_revision: Union[str, Sequence[str], None] = '91bf27a6ecf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_transactions_idempotency_key', 'transactions', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_idempotency_key', 'transactions', type_='unique')
    op.drop_column('transactions', 'idempotency_key')
    # ### end Alembic commands ###
