"""add ledger entry constraints

Revision ID: a3cd23617a3e
Revises: dcf79ba2c49c
Create Date: 2026-09-23 08:40:38.171547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3cd23617a3e'
down_revision: Union[str, Sequence[str], None] = 'dcf79ba2c49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_ledger_entries_ledger_entry_amount_positive'), 'ledger_entries', 'amount > 0')
    op.create_check_constraint(op.f('ck_ledger_entries_ledger_entry_type_check'), 'ledger_entries', "entry_type IN ('DEBIT', 'CREDIT')")
    op.drop_index(op.f('ix_transactions_receiver_wallet_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_sender_wallet_created_at'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_sender_wallet_created_at'), 'transactions', ['sender_wallet_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_receiver_wallet_created_at'), 'transactions', ['receiver_wallet_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('ck_ledger_entries_ledger_entry_type_check'), 'ledger_entries', type_='check')
    op.drop_constraint(op.f('ck_ledger_entries_ledger_entry_amount_positive'), 'ledger_entries', type_='check')
    # ### end Alembic commands ###
